# -*- coding: utf-8 -*-
"""Yet another copy of التطبيق- معسكر البيانات.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y2rPzAAJS93c1q1jTu9Nhaet88D6g4V9

# الاسم / إيمان حسين الحازمي
"""

import pandas as pd

from google.colab import files

uploaded = files.upload()
df = pd.read_csv("exercise.csv")

df.info()

# معلومات احصائية
df.describe()

df.shape

# القيم المفقودة
df.isnull().sum()

df.head()

df.tail()

md_age = df['Age'].median()
df['Age'] =df['Age'].fillna(md_age)

md_duration = df['Duration'].median()
df['Duration'] =df['Duration'].fillna(md_duration)

md_heart_rate = df['Heart_Rate'].median()
df['Heart_Rate'] = df['Heart_Rate'].fillna(md_heart_rate)

md_height = df['Height'].median()
df['Height'] = df['Height'].fillna(md_height)

# القيم المفقودة
df.isnull().sum()

df.to_csv('clesn_exercise.csv' , index=False )

"""


---


---


# المحاضره الرابعة

---



---

"""

df['Age'].value_counts(normalize=True).head()

df['Gender'].value_counts()

df["Weight"].value_counts().max()

df["Weight"].value_counts().min()

deng_weight =df[(df['Gender']== 'male') & (df['Weight'] >= 90 )]

deng_weight.shape[0]

warning = df[(df['Heart_Rate'] > 40) & (df['Heart_Rate'] <= 70)]

warning.shape[0]

df.sort_values('Weight')

df.sort_values('Weight', ascending=False)

df.pivot_table(index='Weight', columns='Gender', values='Calories', aggfunc= 'mean').round()

n_df= n_df = df.select_dtypes(include= "number")

n_df.corr()

"""

---



---

# المحاضره الخامسة



---



---

"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(y=df['Age'], color='red')
plt.title('age-avg')

sns.barplot(x='Gender', y='Weight', data=df)
plt.title('Gender-Weight')

sns.scatterplot(x='Duration', y='Calories', hue='Gender', data=df)

sns.scatterplot(x='Weight', y='Body_Temp', data=df)

sns.countplot(x="Heart_Rate", data=df)
plt.title("Heart_Rate ")

corr_heart = df.drop(columns=['User_ID']).corr(numeric_only=True)

plt.figure(figsize=(10,8))
sns.heatmap(corr_heart, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

Gender_counts = df['Gender'].value_counts()

plt.figure(figsize=(8, 6))
plt.pie(Gender_counts, labels=Gender_counts.index, autopct='%1.1f%%', startangle=90)
plt.title('Gender Distribution')
plt.show()